version: "3.7"
services:
    mongo:
        image: "mongo:latest"
        container_name: mongo_scripts_container
        restart: always
        ports:
            - "27019:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB_DATABASE=admin
        volumes:
            - .:/scripts
